name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deploy script on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER}}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/electra/apps/elek
            git pull origin main
            npm install
            npm run build
            npm run start:prod
